- name: Install the nginx package
  apt: name=nginx-full state=present update_cache=yes

- name: Make sure the sites-available, sites-enabled and conf.d directories exist
  file: path=/etc/nginx/"{{ item }}" state=directory owner=root group=root mode=0755
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "conf.d"

- name: Copy ssl certificats
  command: cp -a /root/ssl "{{ web_user_home_dir }}"

- name: Download config file
  action: template src=templates/server.j2 dest=/etc/nginx/sites-available/server.conf

- name: Generate Diffie-Hellman parameters
  openssl_dhparam:
    path: '{{ web_user_home_dir }}/ssl/dhparams.pem'

- name: Enable the nginx www site
  file: path=/etc/nginx/sites-enabled/server.conf state=link src=/etc/nginx/sites-available/server.conf

- name: delete nginx default conf
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

  notify:
   - restart nginx
