- name: Set MySQL root password before installing
  debconf: 
    name: 'mysql-server' 
    question: 'mysql-server/db_root_passwd' 
    value: '{{db_root_passwd | quote}}' 
    vtype: 'password'
    
- name: Confirm MySQL root password before installing
  debconf: 
    name: 'mysql-server' 
    question: 'mysql-server/db_root_passwd_again' 
    value: '{{db_root_passwd | quote}}' 
    vtype: 'password'
    
- name: install mysql packages
  apt:
   name: ['mysql-server', 'mysql-client', 'python-mysqldb']
   update_cache: yes
   state: latest

- name: Deletes anonymous MySQL server user 
  mysql_user: login_user=root login_password="{{ db_root_passwd }}" user="" host_all=yes state=absent
  
- name: Secures the MySQL root user
  mysql_user: login_user=root login_password="{{ db_root_passwd }}" user=root password="{{ db_root_passwd }}" host="{{ item }}"
  with_items:
    - 127.0.0.1
    - localhost  
    - ::1

- name: Removes the test database
  mysql_db: login_user=root login_password="{{ db_root_passwd }}" db=test state=absent

- name: Create a new database'
  mysql_db: login_user=root login_password="{{ db_root_passwd }}" db="{{ db_name }}" state=present

- name: Create database user with all database privileges
  mysql_user: login_user=root login_password="{{ db_root_passwd }}" name="{{ db_user_name }}" password="{{ db_user_password }}" priv='{{ db_name }}.*:ALL' state=present

  notify:
    - restart php7.2-fpm
