- name: Install some package
  apt:
    name: ['python-minimal', 'libmcrypt-dev']
    state: present
    update_cache: yes

- name: Create www root directory
  file:
    path: /home/www
    state: directory
    mode: '0777'

- name: Add user
  user:
    name: "{{ web_user_name }}"
    group: "{{ web_user_group }}"
    home: "{{ web_user_home_dir }}"
