- name: Install libmcrypt-dev
  apt: name=libmcrypt-dev state=present update_cache=yes

- name: Create www root directory
  file:
    path: /home/www
    state: directory
    mode: '0777'

- name: Add user
  user:
    name: "{{ web_user_name }}"
    home: "{{ web_user_home_dir }}"
    password: "{{ web_user_password }}"
